### ISSUE TITLE
[Bug] Signs not showing stuff (after restart)

### ISSUE THREAD

**Issue by skxlor** [Stardust-Labs-MC/StardustMC#24] opened 2023-08-24 19:49 UTC
### Username

skxlor

### Describe the issue

Writing on hanging signs does not get saved over server restarts. Editing sings does not work and some sings my friends write are empty for me vise versa

**Comment by aisukuma** [comment] 2023-08-26 00:09
Duplicate of #10 (will update that post)

**Closed as completed by aisukuma** 2023-08-26 00:09 UTC
Labels: bug
