### ISSUE TITLE
villager ai is dead in multiple scenarios (have found the fix myself)

### ISSUE THREAD

**Issue by hannafoxie** [Stardust-Labs-MC/StardustMC#5] opened 2023-08-21 01:52 UTC
### Username

abbifox

### Describe the issue

1) villagers get "lobotomized" when they are unable to move causing them to be unable to get/lose a profession making trade halls with an included villager processing part unusable, this also has the side effect of completely breaking stacking raid farms as they rely on villagers gaining and losing their profession to function this can be fixed by changing the villager lobotomization to false in the purpur config

2) villagers refuse to summon an iron golem to defend their village when scared by a zombie/illager this makes iron farms completely broken, this can be fixed by changing the spawn iron golem radius to a number other than 0 in vanilla Minecraft they are summoned within a 17*13*17 cube (8 blocks each way x and z and then 6 blocks up and down)

### Additional context

lobotomization: https://purpurmc.org/docs/Configuration/lobotomize
Iron Golem Spawning: https://purpurmc.org/docs/Configuration/spawn-iron-golem

**Comment by aisukuma** [comment] 2023-08-21 03:56
Fixed. Changes will be applied in the upcoming restart. Will keep this open if the issue is not fixed

**Comment by AnArcticPigeon** [comment] 2023-08-21 08:35
YES !!!! This finally fixed my raid farm, THANK YOU, so the change seems to be working.
Also fixed my iron farm.

**Comment by aisukuma** [comment] 2023-08-21 21:57
Looks like it’s working now. Closing.

**Closed as completed by aisukuma** 2023-08-21 21:57 UTC
Labels: bug
